CREATE TYPE "TemplateScope" AS ENUM ('PLATFORM', 'USER');
CREATE TYPE "VariableMode" AS ENUM ('FIXED', 'RANDOM', 'SEQUENCE');

ALTER TABLE "friends" ADD COLUMN "salutation" TEXT;
ALTER TABLE "tasks" ADD COLUMN "content_template" TEXT, ADD COLUMN "template_snapshot" JSONB, ADD COLUMN "variable_snapshot" JSONB, ADD COLUMN "random_seed" TEXT;
ALTER TABLE "task_messages" ADD COLUMN "recipient_order" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE "friend_groups" ("id" UUID NOT NULL, "owner_id" UUID NOT NULL, "account_id" UUID NOT NULL, "name" TEXT NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "friend_groups_pkey" PRIMARY KEY ("id"));
CREATE TABLE "friend_group_members" ("group_id" UUID NOT NULL, "friend_id" UUID NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "friend_group_members_pkey" PRIMARY KEY ("group_id", "friend_id"));
CREATE TABLE "friend_tags" ("id" UUID NOT NULL, "owner_id" UUID NOT NULL, "account_id" UUID NOT NULL, "name" TEXT NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "friend_tags_pkey" PRIMARY KEY ("id"));
CREATE TABLE "friend_tag_members" ("tag_id" UUID NOT NULL, "friend_id" UUID NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "friend_tag_members_pkey" PRIMARY KEY ("tag_id", "friend_id"));
CREATE TABLE "message_templates" ("id" UUID NOT NULL, "owner_id" UUID, "scope" "TemplateScope" NOT NULL DEFAULT 'USER', "title" TEXT NOT NULL, "content" TEXT NOT NULL, "category" TEXT, "version" INTEGER NOT NULL DEFAULT 1, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "message_templates_pkey" PRIMARY KEY ("id"));
CREATE TABLE "template_favorites" ("owner_id" UUID NOT NULL, "template_id" UUID NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "template_favorites_pkey" PRIMARY KEY ("owner_id", "template_id"));
CREATE TABLE "custom_variables" ("id" UUID NOT NULL, "owner_id" UUID NOT NULL, "name" TEXT NOT NULL, "display_name" TEXT NOT NULL, "mode" "VariableMode" NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "custom_variables_pkey" PRIMARY KEY ("id"));
CREATE TABLE "custom_variable_values" ("id" UUID NOT NULL, "variable_id" UUID NOT NULL, "value" TEXT NOT NULL, "position" INTEGER NOT NULL, CONSTRAINT "custom_variable_values_pkey" PRIMARY KEY ("id"));
CREATE TABLE "task_drafts" ("id" UUID NOT NULL, "owner_id" UUID NOT NULL, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "scheduled_at" TIMESTAMP(3), "payload" JSONB NOT NULL, "source_task_id" UUID, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "task_drafts_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "friend_groups_account_id_name_key" ON "friend_groups"("account_id", "name"); CREATE INDEX "friend_groups_owner_id_account_id_idx" ON "friend_groups"("owner_id", "account_id"); CREATE INDEX "friend_group_members_friend_id_idx" ON "friend_group_members"("friend_id");
CREATE UNIQUE INDEX "friend_tags_account_id_name_key" ON "friend_tags"("account_id", "name"); CREATE INDEX "friend_tags_owner_id_account_id_idx" ON "friend_tags"("owner_id", "account_id"); CREATE INDEX "friend_tag_members_friend_id_idx" ON "friend_tag_members"("friend_id");
CREATE INDEX "message_templates_owner_id_scope_is_active_idx" ON "message_templates"("owner_id", "scope", "is_active");
CREATE UNIQUE INDEX "custom_variables_owner_id_name_key" ON "custom_variables"("owner_id", "name"); CREATE INDEX "custom_variables_owner_id_updated_at_idx" ON "custom_variables"("owner_id", "updated_at"); CREATE UNIQUE INDEX "custom_variable_values_variable_id_position_key" ON "custom_variable_values"("variable_id", "position"); CREATE INDEX "task_drafts_owner_id_updated_at_idx" ON "task_drafts"("owner_id", "updated_at");

ALTER TABLE "friend_groups" ADD CONSTRAINT "friend_groups_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "friend_groups" ADD CONSTRAINT "friend_groups_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "wechat_accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "friend_group_members" ADD CONSTRAINT "friend_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "friend_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "friend_group_members" ADD CONSTRAINT "friend_group_members_friend_id_fkey" FOREIGN KEY ("friend_id") REFERENCES "friends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "friend_tags" ADD CONSTRAINT "friend_tags_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "friend_tags" ADD CONSTRAINT "friend_tags_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "wechat_accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "friend_tag_members" ADD CONSTRAINT "friend_tag_members_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "friend_tags"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "friend_tag_members" ADD CONSTRAINT "friend_tag_members_friend_id_fkey" FOREIGN KEY ("friend_id") REFERENCES "friends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "message_templates" ADD CONSTRAINT "message_templates_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "template_favorites" ADD CONSTRAINT "template_favorites_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "template_favorites" ADD CONSTRAINT "template_favorites_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "message_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "custom_variables" ADD CONSTRAINT "custom_variables_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "custom_variable_values" ADD CONSTRAINT "custom_variable_values_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "custom_variables"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "task_drafts" ADD CONSTRAINT "task_drafts_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "message_templates" ("id", "scope", "title", "content", "category", "version", "updated_at") VALUES
('10000000-0000-4000-8000-000000000001', 'PLATFORM', '节日自然问候', '{{friend_name}}，祝你节日快乐，愿今天轻松顺意，也愿接下来的每一天都有好心情。', '节日问候', 1, CURRENT_TIMESTAMP),
('10000000-0000-4000-8000-000000000002', 'PLATFORM', '活动开始通知', '{{friend_name}}，你好，我们的活动今天正式开始。如你想了解具体内容，我可以把详情整理给你。', '活动通知', 1, CURRENT_TIMESTAMP),
('10000000-0000-4000-8000-000000000003', 'PLATFORM', '价格调整提醒', '{{friend_name}}，你好，之前关注的产品近期有价格调整。如果你还在考虑，我可以把最新方案发给你参考。', '降价提醒', 1, CURRENT_TIMESTAMP),
('10000000-0000-4000-8000-000000000004', 'PLATFORM', '客户回访', '{{friend_name}}，你好，想简单回访一下之前的使用情况。若有任何问题或建议，随时告诉我。', '客户维护', 1, CURRENT_TIMESTAMP);
