import { patch, post, request } from '../../services/api';
const split = (value: string) => [...new Set(value.split(/[，,；;\n\t]+/).map((v) => v.trim()).filter(Boolean))];
Page({
  data: { accounts: [] as any[], accountNames: [] as string[], accountIndex: 0, items: [] as any[], groups: [] as any[], tags: [] as any[], raw: '', parsedCount: 0, showForm: false, error: '', busy: false },
  onShow() { void this.init(); },
  async init() { try { const accounts = await request<any[]>('/accounts'); this.setData({ accounts, accountNames: accounts.map((a) => a.name) }); if (accounts.length) await this.load(); } catch (e) { this.setData({ error: (e as Error).message }); } },
  async load() { const account = this.data.accounts[this.data.accountIndex]; if (account) { const [friends,groups,tags]=await Promise.all([request<any[]>(`/accounts/${account.id}/friends`),request<any[]>(`/accounts/${account.id}/groups`),request<any[]>(`/accounts/${account.id}/tags`)]); const items=friends.map((friend)=>({...friend,groupOptions:groups.map((segment)=>({...segment,selected:segment.friendIds.includes(friend.id)})),tagOptions:tags.map((segment)=>({...segment,selected:segment.friendIds.includes(friend.id)}))})); this.setData({items,groups,tags}); } },
  async accountChange(e: any) { this.setData({ accountIndex: Number(e.detail.value), showForm: false }); await this.load(); },
  toggleForm() { this.setData({ showForm: !this.data.showForm }); },
  rawInput(e: any) { this.setData({ raw: e.detail.value, parsedCount: split(e.detail.value).length }); },
  async chooseFile() { const result = await new Promise<any>((resolve, reject) => wx.chooseMessageFile({ count: 1, type: 'file', success: resolve, fail: reject })); const file = result.tempFiles?.[0]; if (!file) return; this.setData({ busy: true, error: '' }); try { const base64 = await this.readBase64(file.path); const parsed = await post<any>('/imports/friends/file/parse', { fileName: file.name || 'friends.csv', base64 }); this.setData({ raw: parsed.values.join('\n'), parsedCount: parsed.values.length, showForm: true }); } catch (error) { this.setData({ error: (error as Error).message }); } finally { this.setData({ busy: false }); } },
  async chooseImage() { const result = await new Promise<any>((resolve, reject) => wx.chooseImage({ count: 1, sourceType: ['album', 'camera'], success: resolve, fail: reject })); const path = result.tempFilePaths?.[0]; if (!path) return; this.setData({ busy: true, error: '' }); try { const base64 = await this.readBase64(path); const parsed = await post<string[]>('/imports/friends/image/parse', { mimeType: path.toLowerCase().endsWith('.png') ? 'image/png' : 'image/jpeg', imageData: base64 }); this.setData({ raw: parsed.join('\n'), parsedCount: parsed.length, showForm: true }); } catch (error) { this.setData({ error: (error as Error).message }); } finally { this.setData({ busy: false }); } },
  readBase64(path: string) { return new Promise<string>((resolve, reject) => wx.getFileSystemManager().readFile({ filePath: path, encoding: 'base64', success: (result) => resolve(result.data as string), fail: reject })); },
  async create() { const account = this.data.accounts[this.data.accountIndex]; try { await post(`/accounts/${account.id}/friends/bulk`, { remarks: split(this.data.raw) }); this.setData({ raw: '', parsedCount: 0, showForm: false }); await this.load(); } catch (e) { this.setData({ error: (e as Error).message }); } },
  edit(e: any) { const id = e.currentTarget.dataset.id; wx.showModal({ title: '编辑好友备注', editable: true, content: e.currentTarget.dataset.remark, placeholderText: '微信好友备注', success: async (result) => { if (!result.confirm || !result.content?.trim()) return; try { await patch(`/friends/${id}`, { remark: result.content.trim() }); await this.load(); } catch (error) { wx.showToast({ title: (error as Error).message, icon: 'none' }); } } }); },
  editSalutation(e: any) { const id=e.currentTarget.dataset.id; wx.showModal({ title: '设置好友称呼', editable: true, content: e.currentTarget.dataset.salutation || '', placeholderText: '例如：王总（可留空）', success: async (result) => { if (!result.confirm) return; try { await patch(`/friends/${id}`, { salutation: result.content?.trim() || null }); await this.load(); } catch (error) { wx.showToast({ title: (error as Error).message, icon: 'none' }); } } }); },
  async toggle(e: any) { await patch(`/friends/${e.currentTarget.dataset.id}`, { status: e.currentTarget.dataset.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }); await this.load(); },
  createSegment(e: any) { const kind=e.currentTarget.dataset.kind; const account=this.data.accounts[this.data.accountIndex]; wx.showModal({title:`新建${kind==='groups'?'分组':'标签'}`,editable:true,placeholderText:'输入名称',success:async(result)=>{if(!result.confirm||!result.content?.trim())return;try{await post(`/accounts/${account.id}/${kind}`,{name:result.content.trim()});await this.load();}catch(error){wx.showToast({title:(error as Error).message,icon:'none'});}}}); },
  renameSegment(e:any){const kind=e.currentTarget.dataset.kind,id=e.currentTarget.dataset.id,name=e.currentTarget.dataset.name;wx.showModal({title:`重命名${kind==='groups'?'分组':'标签'}`,editable:true,content:name,success:async(result)=>{if(!result.confirm||!result.content?.trim()||result.content.trim()===name)return;try{await patch(`/${kind}/${id}`,{name:result.content.trim()});await this.load();}catch(error){wx.showToast({title:(error as Error).message,icon:'none'});}}});},
  deleteSegment(e:any){const kind=e.currentTarget.dataset.kind,id=e.currentTarget.dataset.id,name=e.currentTarget.dataset.name;wx.showModal({title:`删除${kind==='groups'?'分组':'标签'}“${name}”？`,content:'好友本身不会被删除。',confirmText:'删除',success:async(result)=>{if(!result.confirm)return;try{await post(`/${kind}/${id}/delete`);await this.load();}catch(error){wx.showToast({title:(error as Error).message,icon:'none'});}}});},
  async toggleSegment(e:any){const friend=this.data.items[e.currentTarget.dataset.friendIndex],kind=e.currentTarget.dataset.kind,id=e.currentTarget.dataset.id;const groupIds=friend.groupMemberships.map((item:any)=>item.groupId),tagIds=friend.tagMemberships.map((item:any)=>item.tagId),target=kind==='group'?groupIds:tagIds,index=target.indexOf(id);index>=0?target.splice(index,1):target.push(id);await post(`/friends/${friend.id}/segments`,{groupIds,tagIds});await this.load();},
});
