import { patch, post, request } from '../../services/api';
const split = (value: string) => value.split(/[，,；;\n\t]+/).map((item) => item.trim()).filter(Boolean);
Page({
  data: { items: [] as any[], builtIns: ['{{friend_name}}', '{{date}}', '{{time}}', '{{weekday}}', '{{random_quote}}', '{{warm_greeting}}'], showForm: false, editingId: '', name: '', displayName: '', mode: 'FIXED', modeIndex: 0, modes: ['固定值', '随机取值', '按好友顺序'], modeValues: ['FIXED', 'RANDOM', 'SEQUENCE'], raw: '', error: '' },
  onShow() { void this.load(); },
  async load() { try { const items=await request<any[]>('/variables'); this.setData({ items: items.map((item)=>({...item,token:`{{${item.name}}}`,modeLabel:item.source === 'API' ? '外部 API 动态值 · 任务提交时获取' : `${item.mode === 'FIXED' ? '固定值' : item.mode === 'RANDOM' ? '随机取值' : '按好友顺序'} · ${item.values.length} 个候选值 · V${item.version}`})) }); } catch (error) { this.setData({ error: (error as Error).message }); } },
  toggleForm() { this.setData({ showForm: !this.data.showForm, editingId: '', name: '', displayName: '', mode: 'FIXED', modeIndex: 0, raw: '' }); },
  input(e: any) { this.setData({ [e.currentTarget.dataset.key]: e.detail.value }); },
  modeChange(e: any) { const modeIndex = Number(e.detail.value); this.setData({ modeIndex, mode: this.data.modeValues[modeIndex] }); },
  async importFile() { const result = await new Promise<any>((resolve, reject) => wx.chooseMessageFile({ count: 1, type: 'file', success: resolve, fail: reject })); const file = result.tempFiles?.[0]; if (!file) return; const ask = (title: string, value = '') => new Promise<string>((resolve) => wx.showModal({ title, editable: true, content: value, success: (answer) => resolve(answer.confirm ? answer.content?.trim() || '' : '') })); const name = await ask('变量名（英文）'); if (!name) return; const displayName = await ask('显示名称', name); if (!displayName) return; const modeIndex = await new Promise<number>((resolve, reject) => wx.showActionSheet({ itemList: ['固定值', '随机取值', '按好友顺序'], success: (answer) => resolve(answer.tapIndex), fail: reject })); try { const base64 = await this.readBase64(file.path); await post('/imports/variables/file/import', { fileName: file.name || 'values.csv', base64, name, displayName, mode: ['FIXED', 'RANDOM', 'SEQUENCE'][modeIndex] }); await this.load(); wx.showToast({ title: '导入成功' }); } catch (error) { this.setData({ error: (error as Error).message }); } },
  readBase64(path: string) { return new Promise<string>((resolve, reject) => wx.getFileSystemManager().readFile({ filePath: path, encoding: 'base64', success: (result) => resolve(result.data as string), fail: reject })); },
  edit(e:any) { const item=this.data.items.find((value:any)=>value.id===e.currentTarget.dataset.id); if(!item || item.source === 'API') return; const modeIndex=this.data.modeValues.indexOf(item.mode); this.setData({showForm:true,editingId:item.id,name:item.name,displayName:item.displayName,mode:item.mode,modeIndex,raw:item.values.map((value:any)=>value.value).join('\n')}); },
  async save() { const values = split(this.data.raw); if (!this.data.name.trim() || !this.data.displayName.trim() || !values.length) return; try { const body={ name: this.data.name, displayName: this.data.displayName, mode: this.data.mode, values }; this.data.editingId ? await patch(`/variables/${this.data.editingId}`,body) : await post('/variables', body); this.setData({ showForm: false, editingId: '', name: '', displayName: '', mode: 'FIXED', modeIndex: 0, raw: '' }); await this.load(); } catch (error) { this.setData({ error: (error as Error).message }); } },
});
