import { Check, Clipboard, ExternalLink, KeyRound, Plus, RefreshCw, Settings2 } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ErrorState, LoadingState } from '@/components/states';
import { api, patch, post } from '@/lib/api';
import { AiChannel, ApiIntegration } from '@/types';

type Flag = { key: string; enabled: boolean; config: Record<string, unknown> | null };
const flagLabels: Record<string, string> = { mini_ai_copy: '小程序 AI 生成文案', mini_ai_template: '小程序 AI 生成模板', mini_ai_task: '小程序 AI 生成任务草稿' };

export function AdminPage() {
  const [flags, setFlags] = useState<Flag[]>(); const [channels, setChannels] = useState<AiChannel[]>(); const [integrations, setIntegrations] = useState<ApiIntegration[]>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [channel, setChannel] = useState({ name: '', baseUrl: 'https://api.openai.com/v1', apiKey: '', model: '' }); const [integration, setIntegration] = useState({ name: '', url: '', method: 'GET', variableName: '', displayName: '', responsePath: '', params: '{}' }); const [payment, setPayment] = useState({ amountFen: '1', description: 'WeChatSend 测试付款' }); const [qr, setQr] = useState('');
  const load = async () => { setError(''); try { const [flagData, channelData, apiData] = await Promise.all([api<Flag[]>('/admin/feature-flags'), api<AiChannel[]>('/admin/ai/channels'), api<ApiIntegration[]>('/admin/integrations')]); setFlags(flagData); setChannels(channelData); setIntegrations(apiData); } catch (reason) { setError((reason as Error).message); } };
  useEffect(() => { void load(); }, []);
  const saveChannel = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await post('/admin/ai/channels', { name: channel.name, baseUrl: channel.baseUrl, apiKey: channel.apiKey, models: channel.model ? [{ name: channel.model }] : [] }); setChannel({ name: '', baseUrl: 'https://api.openai.com/v1', apiKey: '', model: '' }); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const saveIntegration = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { let requestParams: Record<string, unknown>; try { requestParams = JSON.parse(integration.params); } catch { throw new Error('请求参数必须是 JSON 对象'); } await post('/admin/integrations', { name: integration.name, url: integration.url, method: integration.method, requestParams, variables: [{ name: integration.variableName, displayName: integration.displayName, responsePath: integration.responsePath }] }); setIntegration({ name: '', url: '', method: 'GET', variableName: '', displayName: '', responsePath: '', params: '{}' }); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const createQr = async () => { setBusy(true); try { const result = await post<{ qrDataUrl: string }>('/payments/qr', { amountFen: Number(payment.amountFen), description: payment.description }); setQr(result.qrDataUrl); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  if (!flags || !channels || !integrations) return error ? <ErrorState message={error} retry={load} /> : <LoadingState />;
  return <div className="page-enter space-y-6"><header className="flex items-end justify-between"><div><p className="font-mono text-[11px] uppercase tracking-[.22em] text-neutral-400">Admin Console</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">平台配置</h1><p className="mt-2 text-sm text-neutral-500">密钥只写入服务端加密字段，列表和日志不会返回明文。</p></div><Button variant="outline" onClick={() => void load()}><RefreshCw className="h-4 w-4" />刷新</Button></header>{error && <ErrorState message={error} />}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 className="h-4 w-4" />小程序 AI 开关</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{flags.map((flag) => <button key={flag.key} className={`rounded-lg border p-4 text-left ${flag.enabled ? 'border-black bg-black text-white' : 'border-neutral-200'}`} onClick={async () => { try { const next = await patch<Flag>(`/admin/feature-flags/${flag.key}`, { enabled: !flag.enabled }); setFlags((items) => (items ?? []).map((item) => item.key === flag.key ? next : item)); } catch (reason) { setError((reason as Error).message); } }}><span className="flex items-center justify-between"><b className="text-sm">{flagLabels[flag.key] || flag.key}</b>{flag.enabled && <Check className="h-4 w-4" />}</span><span className={flag.enabled ? 'text-xs text-neutral-400' : 'text-xs text-neutral-500'}>{flag.enabled ? '已开启' : '已关闭'}</span></button>)}</CardContent></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-4 w-4" />AI 通道</CardTitle></CardHeader><CardContent><div className="space-y-3">{channels.map((item) => <div key={item.id} className="rounded-lg border border-neutral-200 p-4"><div className="flex items-center justify-between"><b>{item.name}</b><span className="text-xs text-neutral-500">{item.isActive ? '启用' : '停用'}</span></div><p className="mt-1 truncate font-mono text-xs text-neutral-400">{item.baseUrl}</p><p className="mt-3 text-xs text-neutral-500">{item.hasApiKey ? 'API Key 已配置' : '未配置密钥'} · {item.models.length} 个模型</p></div>)}{!channels.length && <p className="text-sm text-neutral-500">还没有通道。</p>}</div><form className="mt-5 space-y-3 border-t border-neutral-100 pt-5" onSubmit={saveChannel}><p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">添加通道</p><InputRow label="名称" value={channel.name} onChange={(value) => setChannel({ ...channel, name: value })} placeholder="OpenAI 主通道" /><InputRow label="Base URL（需包含 /v1）" value={channel.baseUrl} onChange={(value) => setChannel({ ...channel, baseUrl: value })} placeholder="https://api.openai.com/v1" /><InputRow label="API Key" value={channel.apiKey} onChange={(value) => setChannel({ ...channel, apiKey: value })} placeholder="sk-..." type="password" /><InputRow label="默认模型名" value={channel.model} onChange={(value) => setChannel({ ...channel, model: value })} placeholder="gpt-4o-mini" /><Button className="w-full" disabled={busy}><Plus className="h-4 w-4" />保存通道</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ExternalLink className="h-4 w-4" />外部 API 变量</CardTitle></CardHeader><CardContent><div className="space-y-3">{integrations.map((item) => <div key={item.id} className="rounded-lg border border-neutral-200 p-4"><div className="flex justify-between"><b>{item.name}</b><span className="text-xs text-neutral-500">{item.method} · {item.enabled ? '启用' : '停用'}</span></div><p className="mt-1 truncate font-mono text-xs text-neutral-400">{item.url}</p><div className="mt-3 flex flex-wrap gap-1.5">{item.variables.map((variable) => <span key={variable.id} className="rounded bg-neutral-100 px-2 py-1 font-mono text-[11px]">{'{{'}{variable.name}{'}}'} → {variable.responsePath}</span>)}</div></div>)}{!integrations.length && <p className="text-sm text-neutral-500">例如配置天气 API，再将 data.weather.text 映射成变量。</p>}</div><form className="mt-5 space-y-3 border-t border-neutral-100 pt-5" onSubmit={saveIntegration}><p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">添加 API 与变量</p><InputRow label="名称" value={integration.name} onChange={(value) => setIntegration({ ...integration, name: value })} placeholder="今日天气" /><InputRow label="URL" value={integration.url} onChange={(value) => setIntegration({ ...integration, url: value })} placeholder="https://example.com/weather" /><label><span className="field-label">方法</span><select className="select" value={integration.method} onChange={(event) => setIntegration({ ...integration, method: event.target.value })}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option></select></label><div className="grid grid-cols-2 gap-3"><InputRow label="变量名" value={integration.variableName} onChange={(value) => setIntegration({ ...integration, variableName: value })} placeholder="weather" /><InputRow label="显示名称" value={integration.displayName} onChange={(value) => setIntegration({ ...integration, displayName: value })} placeholder="今日天气" /></div><InputRow label="响应路径" value={integration.responsePath} onChange={(value) => setIntegration({ ...integration, responsePath: value })} placeholder="data.weather.text" /><label><span className="field-label">请求参数 JSON</span><textarea className="textarea min-h-20 font-mono text-xs" value={integration.params} onChange={(event) => setIntegration({ ...integration, params: event.target.value })} /></label><Button className="w-full" disabled={busy}><Plus className="h-4 w-4" />保存外部 API</Button></form></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Clipboard className="h-4 w-4" />生成小程序付款二维码</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-[160px_1fr_auto] sm:items-end"><InputRow label="金额（分）" value={payment.amountFen} onChange={(value) => setPayment({ ...payment, amountFen: value })} type="number" /><InputRow label="订单描述" value={payment.description} onChange={(value) => setPayment({ ...payment, description: value })} /><Button disabled={busy} onClick={createQr}>生成二维码</Button></div>{qr && <div className="mt-5 flex flex-col items-center gap-3 border-t border-neutral-100 pt-5"><img className="h-56 w-56 border border-neutral-200 p-2" src={qr} alt="小程序付款二维码" /><p className="text-xs text-neutral-500">用户扫码后进入小程序，授权昵称头像并调起微信支付。</p></div>}</CardContent></Card>
  </div>;
}

function InputRow({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className="block"><span className="field-label">{label}</span><input className="h-10 w-full rounded-md border border-neutral-300 bg-white px-3 text-sm outline-none focus:border-black focus:ring-1 focus:ring-black" type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required /></label>; }
