import { FileImage, FileSpreadsheet, FolderPlus, Pencil, Plus, Search, Tag, Trash2, UserRound, UsersRound, X } from 'lucide-react';
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import { api, patch, post } from '@/lib/api';
import { Account, Friend, Segment } from '@/types';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';
import { StatusBadge } from '@/components/status';

function splitRemarks(value: string) { return value.split(/[，,；;\n\t]+/).map((item) => item.trim()).filter(Boolean); }

export function FriendsPage() {
  const [accounts, setAccounts] = useState<Account[]>(); const [accountId, setAccountId] = useState('');
  const [items, setItems] = useState<Friend[]>(); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const [groups, setGroups] = useState<Segment[]>([]); const [tags, setTags] = useState<Segment[]>([]);
  const [showForm, setShowForm] = useState(false); const [raw, setRaw] = useState(''); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<Friend>(); const [editingRemark, setEditingRemark] = useState(''); const [editingSalutation, setEditingSalutation] = useState(''); const [editingGroups, setEditingGroups] = useState<Set<string>>(new Set()); const [editingTags, setEditingTags] = useState<Set<string>>(new Set());
  useEffect(() => { api<Account[]>('/accounts').then((data) => { setAccounts(data); setAccountId((id) => id || data[0]?.id || ''); }).catch((e) => setError(e.message)); }, []);
  const load = () => { if (!accountId) return; Promise.all([api<Friend[]>(`/accounts/${accountId}/friends`), api<Segment[]>(`/accounts/${accountId}/groups`), api<Segment[]>(`/accounts/${accountId}/tags`)]).then(([friends, groupItems, tagItems]) => { setItems(friends); setGroups(groupItems); setTags(tagItems); }).catch((e) => setError(e.message)); };
  useEffect(load, [accountId]);
  const visible = useMemo(() => items?.filter((item) => item.remark.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const remarks = splitRemarks(raw); if (!remarks.length) return; setBusy(true); try { await post(`/accounts/${accountId}/friends/bulk`, { remarks }); setRaw(''); setShowForm(false); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const toggle = async (friend: Friend) => { await patch(`/friends/${friend.id}`, { status: friend.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }); await load(); };
  const openEdit = (friend: Friend) => { setEditing(friend); setEditingRemark(friend.remark); setEditingSalutation(friend.salutation ?? ''); setEditingGroups(new Set(friend.groupMemberships?.map((item) => item.groupId) ?? [])); setEditingTags(new Set(friend.tagMemberships?.map((item) => item.tagId) ?? [])); };
  const saveEdit = async () => { if (!editing || !editingRemark.trim()) return; setBusy(true); try { await patch(`/friends/${editing.id}`, { remark: editingRemark, salutation: editingSalutation || null }); await post(`/friends/${editing.id}/segments`, { groupIds: [...editingGroups], tagIds: [...editingTags] }); setEditing(undefined); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const createSegment = async (kind: 'groups'|'tags') => { const name = prompt(`输入${kind === 'groups' ? '分组' : '标签'}名称`); if (!name?.trim()) return; try { await post(`/accounts/${accountId}/${kind}`, { name: name.trim() }); await load(); } catch (e) { setError((e as Error).message); } };
  const renameSegment = async (kind: 'groups'|'tags', item: Segment) => { const name = prompt(`重命名${kind === 'groups' ? '分组' : '标签'}`, item.name); if (!name?.trim() || name.trim() === item.name) return; try { await patch(`/${kind}/${item.id}`, { name: name.trim() }); await load(); } catch (e) { setError((e as Error).message); } };
  const removeSegment = async (kind: 'groups'|'tags', item: Segment) => { if (!confirm(`删除${kind === 'groups' ? '分组' : '标签'}“${item.name}”？好友本身不会被删除。`)) return; try { await post(`/${kind}/${item.id}/delete`); await load(); } catch (e) { setError((e as Error).message); } };
  const toggleSet = (current: Set<string>, id: string, setter: (value: Set<string>) => void) => { const copy = new Set(current); copy.has(id) ? copy.delete(id) : copy.add(id); setter(copy); };
  const parsed = splitRemarks(raw);
  const readBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = () => reject(new Error('读取文件失败')); reader.readAsDataURL(file); });
  const importSheet = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setBusy(true); setError(''); try { const base64 = await readBase64(file); const result = await post<{ values: string[] }>('/imports/friends/file/parse', { fileName: file.name, base64 }); setRaw(result.values.join('\n')); setShowForm(true); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const importImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setBusy(true); setError(''); try { const base64 = await readBase64(file); const result = await post<string[]>('/imports/friends/image/parse', { mimeType: file.type, imageData: base64 }); setRaw(result.join('\n')); setShowForm(true); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  return <div className="page-enter space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.22em] text-neutral-400">Contacts</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">好友管理</h1><p className="mt-2 text-sm text-neutral-500">好友以微信备注匹配，同一个发送账号下不可重名。</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-neutral-300 bg-white px-4 text-sm font-medium hover:bg-neutral-100"><FileSpreadsheet className="h-4 w-4" />导入表格<input hidden type="file" accept=".csv,.xlsx,.xls" onChange={importSheet} /></label><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-neutral-300 bg-white px-4 text-sm font-medium hover:bg-neutral-100"><FileImage className="h-4 w-4" />截图识别<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={importImage} /></label><Button disabled={!accountId || busy} onClick={() => setShowForm(true)}><Plus className="h-4 w-4" />添加好友</Button></div></header>{error && <ErrorState message={error} />}
    <Card className="flex flex-col gap-3 p-4 sm:flex-row"><select className="select sm:max-w-xs" value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">选择发送账号</option>{accounts?.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-400" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="搜索好友备注" /></label><Button variant="outline" onClick={() => createSegment('groups')}><FolderPlus className="h-4 w-4" />新建分组</Button><Button variant="outline" onClick={() => createSegment('tags')}><Tag className="h-4 w-4" />新建标签</Button></Card>
    {(groups.length > 0 || tags.length > 0) && <Card className="space-y-4 p-4"><div><p className="field-label">好友分组</p><div className="flex flex-wrap gap-2">{groups.map((item) => <span key={item.id} className="inline-flex items-center overflow-hidden rounded-full border border-neutral-200 text-xs"><span className="px-3 py-1.5">{item.name} · {item.friendIds.length}</span><button className="border-l p-1.5 hover:bg-neutral-100" onClick={() => renameSegment('groups', item)} aria-label={`重命名${item.name}`}><Pencil className="h-3 w-3" /></button><button className="border-l p-1.5 hover:bg-red-50 hover:text-red-600" onClick={() => removeSegment('groups', item)} aria-label={`删除${item.name}`}><Trash2 className="h-3 w-3" /></button></span>)}</div></div><div><p className="field-label">好友标签</p><div className="flex flex-wrap gap-2">{tags.map((item) => <span key={item.id} className="inline-flex items-center overflow-hidden rounded-full border border-dashed border-neutral-300 text-xs"><span className="px-3 py-1.5">#{item.name} · {item.friendIds.length}</span><button className="border-l p-1.5 hover:bg-neutral-100" onClick={() => renameSegment('tags', item)} aria-label={`重命名${item.name}`}><Pencil className="h-3 w-3" /></button><button className="border-l p-1.5 hover:bg-red-50 hover:text-red-600" onClick={() => removeSegment('tags', item)} aria-label={`删除${item.name}`}><Trash2 className="h-3 w-3" /></button></span>)}</div></div></Card>}
    {!accounts || (accountId && !items) ? <LoadingState /> : !accountId ? <EmptyState title="请先添加发送账号" detail="好友必须归属于一个发送账号。" /> : visible?.length === 0 ? <EmptyState title={search ? '没有匹配的好友' : '还没有好友'} detail={search ? '换一个关键词试试。' : '可用逗号、分号、换行一次粘贴多个微信好友备注。'} action={!search ? { label: '添加好友', onClick: () => setShowForm(true) } : undefined} /> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visible?.map((friend) => <Card key={friend.id} className="flex items-center gap-4 p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-neutral-100"><UserRound className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate font-medium">{friend.remark}</p>{friend.salutation && <p className="truncate text-xs text-neutral-400">称呼 · {friend.salutation}</p>}<div className="mt-2 flex flex-wrap gap-1">{groups.filter((group) => group.friendIds.includes(friend.id)).map((group) => <span key={group.id} className="rounded bg-neutral-100 px-1.5 py-0.5 text-[10px]">{group.name}</span>)}{tags.filter((tag) => tag.friendIds.includes(friend.id)).map((tag) => <span key={tag.id} className="rounded border border-dashed px-1.5 py-0.5 text-[10px]">#{tag.name}</span>)}</div><div className="mt-1"><StatusBadge status={friend.status} /></div></div><div className="flex"><Button variant="ghost" size="sm" onClick={() => openEdit(friend)}>编辑</Button><Button variant="ghost" size="sm" onClick={() => toggle(friend)}>{friend.status === 'ACTIVE' ? '停用' : '启用'}</Button></div></Card>)}</div>}
    {showForm && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 sm:items-center sm:p-4" onClick={() => setShowForm(false)}><Card className="w-full max-w-xl rounded-b-none p-6 shadow-2xl sm:rounded-xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">批量添加好友</h2><p className="mt-1 text-sm text-neutral-500">中英文逗号、分号或换行均可识别；表格或截图会先进入这里确认。</p></div><Button variant="ghost" size="icon" onClick={() => setShowForm(false)}><X className="h-4 w-4" /></Button></div><form className="mt-6" onSubmit={submit}><label><span className="field-label">微信好友备注</span><textarea className="textarea min-h-44" value={raw} onChange={(e) => setRaw(e.target.value)} placeholder={'凯旋，宇航\n张经理；李老师'} /></label><div className="mt-4 flex items-center justify-between rounded-lg bg-neutral-100 px-4 py-3 text-sm"><span className="flex items-center gap-2"><UsersRound className="h-4 w-4" />已识别 {parsed.length} 个备注</span><span className="text-xs text-neutral-500">重复项自动跳过</span></div><Button className="mt-5 w-full" disabled={busy || !parsed.length}>{busy ? '正在导入…' : `确认导入 ${parsed.length} 位好友`}</Button></form></Card></div>}
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4" onClick={() => setEditing(undefined)}><Card className="w-full max-w-lg p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><h2 className="text-xl font-semibold">编辑好友</h2><p className="mt-2 text-sm text-neutral-500">微信备注用于匹配；好友称呼用于变量 <code>{'{{friend_name}}'}</code>。</p><div className="mt-6 grid grid-cols-2 gap-3"><label><span className="field-label">微信好友备注</span><Input value={editingRemark} onChange={(e) => setEditingRemark(e.target.value)} /></label><label><span className="field-label">好友称呼（选填）</span><Input value={editingSalutation} onChange={(e) => setEditingSalutation(e.target.value)} placeholder="例如：王总" /></label></div><p className="field-label mt-5">分组</p><div className="flex flex-wrap gap-2">{groups.map((item) => <button type="button" key={item.id} onClick={() => toggleSet(editingGroups,item.id,setEditingGroups)} className={editingGroups.has(item.id) ? 'rounded-full bg-emerald-700 px-3 py-1.5 text-xs text-white' : 'rounded-full border px-3 py-1.5 text-xs'}>{item.name}</button>)}</div><p className="field-label mt-5">标签</p><div className="flex flex-wrap gap-2">{tags.map((item) => <button type="button" key={item.id} onClick={() => toggleSet(editingTags,item.id,setEditingTags)} className={editingTags.has(item.id) ? 'rounded-full bg-emerald-700 px-3 py-1.5 text-xs text-white' : 'rounded-full border border-dashed px-3 py-1.5 text-xs'}>#{item.name}</button>)}</div><div className="mt-6 flex gap-3"><Button variant="outline" className="flex-1" onClick={() => setEditing(undefined)}>取消</Button><Button className="flex-1" disabled={busy} onClick={saveEdit}>保存</Button></div></Card></div>}
  </div>;
}
