import { ArrowLeft, Check, Clock, Send, UsersRound } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, post } from '@/lib/api';
import { Account, Friend, Task } from '@/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';
import { cn } from '@/lib/utils';

type Selection = { account: Account; friends: Friend[]; selected: Set<string>; minDelay: number; maxDelay: number };

function localDateTimeValue(date = new Date()) {
  const offset = date.getTimezoneOffset() * 60_000;
  return new Date(date.getTime() - offset).toISOString().slice(0, 16);
}

export function TaskNewPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [accounts, setAccounts] = useState<Account[]>();
  const [selections, setSelections] = useState<Record<string, Selection>>({}); const [title, setTitle] = useState(''); const [content, setContent] = useState('');
  const [timing, setTiming] = useState<'now'|'later'>('now'); const [scheduledAt, setScheduledAt] = useState(() => localDateTimeValue()); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api<Account[]>('/accounts').then(async (data) => { const active = data.filter((a) => a.status === 'ACTIVE'); setAccounts(active); const result: Record<string, Selection> = {}; await Promise.all(active.map(async (account) => { const friends = await api<Friend[]>(`/accounts/${account.id}/friends`); result[account.id] = { account, friends: friends.filter((f) => f.status === 'ACTIVE'), selected: new Set(), minDelay: account.minDelay, maxDelay: account.maxDelay }; })); setSelections(result); }).catch((e) => setError(e.message)); }, []);
  const total = useMemo(() => Object.values(selections).reduce((sum, item) => sum + item.selected.size, 0), [selections]);
  const toggle = (accountId: string, friendId: string) => setSelections((current) => { const copy = { ...current, [accountId]: { ...current[accountId], selected: new Set(current[accountId].selected) } }; copy[accountId].selected.has(friendId) ? copy[accountId].selected.delete(friendId) : copy[accountId].selected.add(friendId); return copy; });
  const next = () => { setError(''); if (step === 1 && (!title.trim() || !content.trim())) return setError('请填写任务名称和消息内容'); if (step === 2 && total === 0) return setError('请至少选择一位好友'); if (step === 3 && Object.values(selections).some((s) => s.selected.size && (s.minDelay < 10 || s.maxDelay < 10 || s.minDelay > s.maxDelay))) return setError('发送间隔至少 10 秒，且最小值不能大于最大值'); if (step === 3 && timing === 'later' && !scheduledAt) return setError('请选择定时时间'); setStep((value) => Math.min(4, value + 1)); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const body = { title, content, idempotencyKey: crypto.randomUUID(), ...(timing === 'later' ? { scheduledAt: new Date(scheduledAt).toISOString() } : {}), selections: Object.values(selections).filter((s) => s.selected.size).map((s) => ({ accountId: s.account.id, friendIds: [...s.selected], minDelay: s.minDelay, maxDelay: s.maxDelay })) }; const task = await post<Task>('/tasks', body); navigate(`/tasks/${task.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  if (!accounts) return <LoadingState />;
  if (!accounts.length) return <EmptyState title="请先添加发送账号" detail="创建任务前，需要至少一个启用且已验证邮箱的发送账号。" action={{ label: '去添加账号', onClick: () => navigate('/accounts') }} />;
  return <form className="page-enter" onSubmit={submit}><div className="mb-7 flex items-center gap-3"><Button asChild variant="ghost" size="icon"><Link to="/tasks"><ArrowLeft className="h-4 w-4" /></Link></Button><div><p className="font-mono text-[11px] uppercase tracking-[.22em] text-neutral-400">New dispatch</p><h1 className="mt-1 text-2xl font-semibold">创建发送任务</h1></div></div><div className="mb-7 grid grid-cols-4 overflow-hidden rounded-lg border border-neutral-200 bg-white">{['写文案','选好友','定时间','确认'].map((label, index) => <button type="button" key={label} onClick={() => index + 1 < step && setStep(index + 1)} className={cn('border-r border-neutral-200 px-2 py-3 text-xs last:border-0 sm:text-sm', step === index + 1 ? 'bg-black text-white' : index + 1 < step ? 'text-black' : 'text-neutral-400')}><span className="mr-1 font-mono">0{index + 1}</span> {label}</button>)}</div>{error && <div className="mb-5"><ErrorState message={error} /></div>}
    {step === 1 && <Card><CardHeader><CardTitle>消息内容</CardTitle></CardHeader><CardContent className="space-y-5"><label><span className="field-label">任务名称</span><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="例如：中秋节客户问候" maxLength={100} /></label><label><span className="field-label">微信消息</span><textarea className="textarea min-h-52" value={content} onChange={(e) => setContent(e.target.value)} placeholder="输入或粘贴纯文本消息…" maxLength={10000} /><span className="field-help">本阶段仅支持纯文本。任务提交后会冻结内容。</span></label></CardContent></Card>}
    {step === 2 && <div className="space-y-4">{Object.values(selections).map((selection) => <Card key={selection.account.id}><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{selection.account.name}</CardTitle><p className="mt-1 text-xs text-neutral-500">{selection.account.recipientEmail}</p></div><span className="font-mono text-sm">{selection.selected.size}/{selection.friends.length}</span></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{selection.friends.map((friend) => <button type="button" key={friend.id} onClick={() => toggle(selection.account.id, friend.id)} className={cn('flex items-center rounded-lg border px-3 py-3 text-left text-sm transition-colors', selection.selected.has(friend.id) ? 'border-black bg-black text-white' : 'border-neutral-200 hover:border-neutral-400')}><span className={cn('mr-3 flex h-5 w-5 items-center justify-center rounded border', selection.selected.has(friend.id) ? 'border-white' : 'border-neutral-300')}>{selection.selected.has(friend.id) && <Check className="h-3 w-3" />}</span><span className="truncate">{friend.remark}</span></button>)}</div>{!selection.friends.length && <p className="text-sm text-neutral-500">该账号暂无启用好友。</p>}</CardContent></Card>)}</div>}
    {step === 3 && <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>开始时间</CardTitle></CardHeader><CardContent className="space-y-3"><button type="button" onClick={() => setTiming('now')} className={cn('flex w-full items-center rounded-lg border p-4 text-left', timing === 'now' ? 'border-black ring-1 ring-black' : 'border-neutral-200')}><Send className="mr-3 h-4 w-4" /><span><b className="block text-sm">立即发送</b><small className="text-neutral-500">提交后进入服务端队列</small></span></button><button type="button" onClick={() => { setTiming('later'); if (new Date(scheduledAt).getTime() < Date.now()) setScheduledAt(localDateTimeValue()); }} className={cn('flex w-full items-center rounded-lg border p-4 text-left', timing === 'later' ? 'border-black ring-1 ring-black' : 'border-neutral-200')}><Clock className="mr-3 h-4 w-4" /><span><b className="block text-sm">单次定时</b><small className="text-neutral-500">到达时间后开始排队</small></span></button>{timing === 'later' && <Input type="datetime-local" min={localDateTimeValue()} value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} />}</CardContent></Card><Card><CardHeader><CardTitle>发送间隔</CardTitle></CardHeader><CardContent className="space-y-4">{Object.values(selections).filter((s) => s.selected.size).map((s) => <div key={s.account.id}><p className="mb-2 text-sm font-medium">{s.account.name}</p><div className="grid grid-cols-2 gap-3"><label><span className="field-label">最小秒数</span><Input type="number" min="10" value={s.minDelay} onChange={(e) => setSelections((v) => ({ ...v, [s.account.id]: { ...v[s.account.id], minDelay: Number(e.target.value) } }))} /></label><label><span className="field-label">最大秒数</span><Input type="number" min="10" value={s.maxDelay} onChange={(e) => setSelections((v) => ({ ...v, [s.account.id]: { ...v[s.account.id], maxDelay: Number(e.target.value) } }))} /></label></div></div>)}</CardContent></Card></div>}
    {step === 4 && <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap rounded-lg bg-neutral-100 p-4 text-sm leading-7">{content}</p></CardContent></Card><Card><CardHeader><CardTitle>发送确认</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><p className="flex items-center justify-between"><span className="text-neutral-500">接收好友</span><b>{total} 人</b></p><p className="flex items-center justify-between"><span className="text-neutral-500">发送账号</span><b>{Object.values(selections).filter((s) => s.selected.size).length} 个</b></p><p className="flex items-center justify-between"><span className="text-neutral-500">开始时间</span><b>{timing === 'now' ? '立即' : new Date(scheduledAt).toLocaleString('zh-CN')}</b></p><div className="rounded-lg border border-neutral-200 p-3 text-xs leading-5 text-neutral-500">确认后，每位好友将生成一封标签文本邮件。邮件成功不代表微信已送达。</div></CardContent></Card></div>}
    <div className="mt-6 flex items-center justify-between"><Button type="button" variant="outline" disabled={step === 1} onClick={() => setStep((value) => value - 1)}>上一步</Button><div className="flex items-center gap-3 text-sm text-neutral-500"><UsersRound className="h-4 w-4" />{total} 位好友</div>{step < 4 ? <Button type="button" onClick={next}>下一步</Button> : <Button disabled={busy}>{busy ? '正在创建…' : '确认并提交'}</Button>}</div></form>;
}
