import { ArrowLeft, BookOpenText, Check, Clock, Save, Send, UsersRound } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';
import { api, patch, post } from '@/lib/api';
import { cn } from '@/lib/utils';
import { Account, CustomVariable, Friend, MessageTemplate, Segment, Task, TaskDraft } from '@/types';

type Selection = { account: Account; friends: Friend[]; groups: Segment[]; tags: Segment[]; selected: Set<string>; minDelay: number; maxDelay: number };
type Preview = { renderSeed: string; previewFingerprint: string; recipients: Array<{ friendRemark: string; content: string }> };
const builtIns = [{ name: 'friend_name', label: '好友称呼' }, { name: 'date', label: '日期' }, { name: 'time', label: '时间' }, { name: 'weekday', label: '星期' }, { name: 'random_quote', label: '随机语录' }, { name: 'warm_greeting', label: '温馨问候' }];

function localDateTimeValue(date = new Date()) { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }

export function TaskNewPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const draftId = params.get('draft'); const templateParam = params.get('template'); const contentParam = params.get('content');
  const [step, setStep] = useState(1); const [accounts, setAccounts] = useState<Account[]>(); const [selections, setSelections] = useState<Record<string, Selection>>({});
  const [templates, setTemplates] = useState<MessageTemplate[]>([]); const [variables, setVariables] = useState<CustomVariable[]>([]); const [templateId, setTemplateId] = useState<string | null>(null);
  const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [timing, setTiming] = useState<'now'|'later'>('now'); const [scheduledAt, setScheduledAt] = useState(localDateTimeValue());
  const [renderSeed, setRenderSeed] = useState<string>(() => crypto.randomUUID()); const [preview, setPreview] = useState<Preview>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [savedDraftId, setSavedDraftId] = useState<string | null>(draftId);

  useEffect(() => { void (async () => { try {
    const [accountData, templateData, variableData, draft] = await Promise.all([
      api<Account[]>('/accounts'), api<MessageTemplate[]>('/templates'), api<CustomVariable[]>('/variables'), draftId ? api<TaskDraft>(`/drafts/${draftId}`) : Promise.resolve(undefined),
    ]);
    const active = accountData.filter((account) => account.status === 'ACTIVE'); const result: Record<string, Selection> = {};
    await Promise.all(active.map(async (account) => { const [friends, groups, tags] = await Promise.all([api<Friend[]>(`/accounts/${account.id}/friends`), api<Segment[]>(`/accounts/${account.id}/groups`), api<Segment[]>(`/accounts/${account.id}/tags`)]); result[account.id] = { account, friends: friends.filter((friend) => friend.status === 'ACTIVE'), groups, tags, selected: new Set(), minDelay: account.minDelay, maxDelay: account.maxDelay }; }));
    setAccounts(active); setTemplates(templateData); setVariables(variableData);
    const selectedTemplate = templateData.find((item) => item.id === templateParam);
    if (selectedTemplate) { setTemplateId(selectedTemplate.id); setContent(selectedTemplate.content); setTitle(selectedTemplate.title); }
    if (contentParam && !draft) setContent(contentParam);
    if (draft) {
      setTitle(draft.title); setContent(draft.content); setTemplateId(draft.payload.templateId ?? null);
      if (draft.payload.renderSeed) setRenderSeed(draft.payload.renderSeed);
      if (draft.scheduledAt) { setTiming('later'); setScheduledAt(localDateTimeValue(new Date(draft.scheduledAt))); }
      for (const saved of draft.payload.selections ?? []) if (result[saved.accountId]) {
        const activeIds = new Set(result[saved.accountId].friends.map((friend) => friend.id));
        result[saved.accountId] = { ...result[saved.accountId], selected: new Set(saved.friendIds.filter((id) => activeIds.has(id))), minDelay: saved.minDelay ?? result[saved.accountId].minDelay, maxDelay: saved.maxDelay ?? result[saved.accountId].maxDelay };
      }
    }
    setSelections(result);
  } catch (reason) { setError((reason as Error).message); } })(); }, [contentParam, draftId, templateParam]);

  const total = useMemo(() => Object.values(selections).reduce((sum, item) => sum + item.selected.size, 0), [selections]);
  const toggle = (accountId: string, friendId: string) => setSelections((current) => { const selected = new Set(current[accountId].selected); selected.has(friendId) ? selected.delete(friendId) : selected.add(friendId); return { ...current, [accountId]: { ...current[accountId], selected } }; });
  const selectSegment = (accountId: string, segment: Segment) => setSelections((current) => { const selected = new Set(current[accountId].selected); const activeIds = segment.friendIds.filter((id) => current[accountId].friends.some((friend) => friend.id === id)); const allSelected = activeIds.length > 0 && activeIds.every((id) => selected.has(id)); activeIds.forEach((id) => allSelected ? selected.delete(id) : selected.add(id)); return { ...current, [accountId]: { ...current[accountId], selected } }; });
  const taskBody = () => ({ title, content, templateId, renderSeed, ...(timing === 'later' ? { scheduledAt: new Date(scheduledAt).toISOString() } : {}), selections: Object.values(selections).filter((selection) => selection.selected.size).map((selection) => ({ accountId: selection.account.id, friendIds: [...selection.selected], groupIds: [], tagIds: [], minDelay: selection.minDelay, maxDelay: selection.maxDelay })) });
  const validate = () => { if (!title.trim() || !content.trim()) return '请填写任务名称和消息内容'; if (!total) return '请至少选择一位好友'; if (Object.values(selections).some((s) => s.selected.size && (s.minDelay < 10 || s.maxDelay < 10 || s.minDelay > s.maxDelay))) return '发送间隔至少 10 秒，且最小值不能大于最大值'; if (timing === 'later' && !scheduledAt) return '请选择定时时间'; return ''; };
  const next = async () => { const issue = step === 1 && (!title.trim() || !content.trim()) ? '请填写任务名称和消息内容' : step === 2 && !total ? '请至少选择一位好友' : step === 3 ? validate() : ''; if (issue) return setError(issue); setError(''); const nextStep = Math.min(4, step + 1); setStep(nextStep); if (nextStep === 4) { try { setPreview(await post<Preview>('/tasks/preview', taskBody())); } catch (reason) { setError((reason as Error).message); } } };
  const saveDraft = async () => { setBusy(true); setError(''); try { const body = taskBody(); const draft = savedDraftId ? await patch<TaskDraft>(`/drafts/${savedDraftId}`, body) : await post<TaskDraft>('/drafts', body); setSavedDraftId(draft.id); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); const issue = validate(); if (issue) return setError(issue); if (!preview) return setError('请先生成最终文案预览'); setBusy(true); try { const task = await post<Task>('/tasks', { ...taskBody(), previewFingerprint: preview.previewFingerprint, idempotencyKey: crypto.randomUUID() }); if (savedDraftId) await post(`/drafts/${savedDraftId}/delete`).catch(() => undefined); navigate(`/tasks/${task.id}`); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const chooseTemplate = (id: string) => { const item = templates.find((template) => template.id === id); setTemplateId(id || null); if (item) { setContent(item.content); if (!title) setTitle(item.title); } };
  const insertVariable = (name: string) => setContent((value) => `${value}${value && !value.endsWith(' ') ? ' ' : ''}{{${name}}}`);
  if (!accounts) return <LoadingState />;
  if (!accounts.length) return <EmptyState title="请先添加发送账号" detail="创建任务前，需要至少一个启用且已验证邮箱的发送账号。" action={{ label: '去添加账号', onClick: () => navigate('/accounts') }} />;

  return <form className="page-enter" onSubmit={submit}><div className="mb-7 flex flex-wrap items-center gap-3"><Button asChild variant="ghost" size="icon"><Link to="/tasks"><ArrowLeft className="h-4 w-4" /></Link></Button><div className="mr-auto"><p className="font-mono text-[11px] uppercase tracking-[.22em] text-neutral-400">New dispatch · P2</p><h1 className="mt-1 text-2xl font-semibold">{savedDraftId ? '继续编辑草稿' : '创建发送任务'}</h1></div><Button type="button" variant="outline" disabled={busy} onClick={saveDraft}><Save className="h-4 w-4" />保存草稿</Button></div>
    <div className="mb-7 grid grid-cols-4 overflow-hidden rounded-lg border border-neutral-200 bg-white">{['写文案','选好友','定时间','确认'].map((label,index) => <button type="button" key={label} onClick={() => index + 1 < step && setStep(index + 1)} className={cn('border-r border-neutral-200 px-2 py-3 text-xs last:border-0 sm:text-sm', step === index + 1 ? 'bg-emerald-700 text-white' : index + 1 < step ? 'text-emerald-800' : 'text-neutral-400')}><span className="mr-1 font-mono">0{index + 1}</span> {label}</button>)}</div>{error && <div className="mb-5"><ErrorState message={error} /></div>}
    {step === 1 && <div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><Card><CardHeader><CardTitle>消息内容</CardTitle></CardHeader><CardContent className="space-y-5"><label><span className="field-label">任务名称</span><Input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={100} /></label><label><span className="field-label">选择模板</span><select className="select" value={templateId ?? ''} onChange={(e) => chooseTemplate(e.target.value)}><option value="">不使用模板</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.scope === 'PLATFORM' ? '精选 · ' : '我的 · '}{item.title}</option>)}</select></label><label><span className="field-label">微信消息</span><textarea className="textarea min-h-64" value={content} onChange={(e) => setContent(e.target.value)} maxLength={10000} /><span className="field-help">可插入变量；提交时为每位好友生成并冻结最终文案。</span></label></CardContent></Card><Card><CardHeader><CardTitle>插入变量</CardTitle></CardHeader><CardContent><p className="mb-3 text-xs text-neutral-400">内置变量</p><div className="flex flex-wrap gap-2">{builtIns.map((item) => <button type="button" key={item.name} onClick={() => insertVariable(item.name)} className="rounded-lg border border-neutral-200 px-3 py-2 text-left text-xs hover:border-emerald-500"><b className="block font-mono">{`{{${item.name}}}`}</b><span className="text-neutral-400">{item.label}</span></button>)}</div><p className="mb-3 mt-6 text-xs text-neutral-400">我的变量</p><div className="flex flex-wrap gap-2">{variables.map((item) => <button type="button" key={item.id} onClick={() => insertVariable(item.name)} className="rounded-lg border border-neutral-200 px-3 py-2 text-xs hover:border-emerald-500"><b className="font-mono">{`{{${item.name}}}`}</b><span className="ml-2 text-neutral-400">{item.displayName}</span></button>)}{!variables.length && <p className="text-xs text-neutral-400">尚未创建自定义变量。</p>}</div></CardContent></Card></div>}
    {step === 2 && <div className="space-y-4">{Object.values(selections).map((selection) => <Card key={selection.account.id}><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{selection.account.name}</CardTitle><p className="mt-1 text-xs text-neutral-500">{selection.account.recipientEmail}</p></div><span className="font-mono text-sm">{selection.selected.size}/{selection.friends.length}</span></CardHeader><CardContent>{(selection.groups.length > 0 || selection.tags.length > 0) && <div className="mb-4 border-b border-neutral-100 pb-4"><p className="mb-2 text-xs text-neutral-400">按分组/标签快速选择（与手动选择自动去重）</p><div className="flex flex-wrap gap-2">{selection.groups.map((item) => <button type="button" key={item.id} onClick={() => selectSegment(selection.account.id,item)} className="rounded-full border border-emerald-600 px-3 py-1.5 text-xs text-emerald-800">分组 · {item.name} · {item.friendIds.length}</button>)}{selection.tags.map((item) => <button type="button" key={item.id} onClick={() => selectSegment(selection.account.id,item)} className="rounded-full border border-neutral-300 border-dashed px-3 py-1.5 text-xs">#{item.name} · {item.friendIds.length}</button>)}</div></div>}<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{selection.friends.map((friend) => <button type="button" key={friend.id} onClick={() => toggle(selection.account.id, friend.id)} className={cn('flex items-center rounded-lg border px-3 py-3 text-left text-sm', selection.selected.has(friend.id) ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-neutral-200 hover:border-neutral-400')}><span className={cn('mr-3 flex h-5 w-5 items-center justify-center rounded border', selection.selected.has(friend.id) ? 'border-white' : 'border-neutral-300')}>{selection.selected.has(friend.id) && <Check className="h-3 w-3" />}</span><span><span className="block truncate">{friend.remark}</span>{friend.salutation && <small className="opacity-60">称呼：{friend.salutation}</small>}</span></button>)}</div></CardContent></Card>)}</div>}
    {step === 3 && <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>开始时间</CardTitle></CardHeader><CardContent className="space-y-3"><button type="button" onClick={() => setTiming('now')} className={cn('flex w-full items-center rounded-lg border p-4 text-left', timing === 'now' ? 'border-emerald-600 ring-1 ring-emerald-600' : 'border-neutral-200')}><Send className="mr-3 h-4 w-4" /><span><b className="block text-sm">立即发送</b><small className="text-neutral-500">提交后进入服务端队列</small></span></button><button type="button" onClick={() => setTiming('later')} className={cn('flex w-full items-center rounded-lg border p-4 text-left', timing === 'later' ? 'border-emerald-600 ring-1 ring-emerald-600' : 'border-neutral-200')}><Clock className="mr-3 h-4 w-4" /><span><b className="block text-sm">单次定时</b><small className="text-neutral-500">到达时间后开始排队</small></span></button>{timing === 'later' && <Input type="datetime-local" min={localDateTimeValue()} value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} />}</CardContent></Card><Card><CardHeader><CardTitle>发送间隔</CardTitle></CardHeader><CardContent className="space-y-4">{Object.values(selections).filter((s) => s.selected.size).map((s) => <div key={s.account.id}><p className="mb-2 text-sm font-medium">{s.account.name}</p><div className="grid grid-cols-2 gap-3"><Input type="number" min="10" value={s.minDelay} onChange={(e) => setSelections((v) => ({ ...v, [s.account.id]: { ...v[s.account.id], minDelay: Number(e.target.value) } }))} /><Input type="number" min="10" value={s.maxDelay} onChange={(e) => setSelections((v) => ({ ...v, [s.account.id]: { ...v[s.account.id], maxDelay: Number(e.target.value) } }))} /></div></div>)}</CardContent></Card></div>}
    {step === 4 && <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle>最终文案预览</CardTitle></CardHeader><CardContent className="space-y-3">{preview?.recipients.slice(0,8).map((item,index) => <div key={`${item.friendRemark}-${index}`} className="rounded-lg border border-neutral-200 p-4"><p className="mb-2 text-xs font-semibold text-neutral-400">{item.friendRemark}</p><p className="whitespace-pre-wrap text-sm leading-7">{item.content}</p></div>)}{!preview && <LoadingState />}</CardContent></Card><Card><CardHeader><CardTitle>发送确认</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><p className="flex justify-between"><span className="text-neutral-500">接收好友</span><b>{total} 人</b></p><p className="flex justify-between"><span className="text-neutral-500">发送账号</span><b>{Object.values(selections).filter((s) => s.selected.size).length} 个</b></p><div className="rounded-lg border border-neutral-200 p-3 text-xs leading-5 text-neutral-500">预览与发送使用相同随机种子。模板和变量候选值将在提交时冻结。</div></CardContent></Card></div>}
    <div className="mt-6 flex items-center justify-between"><Button type="button" variant="outline" disabled={step === 1} onClick={() => setStep((value) => value - 1)}>上一步</Button><div className="flex items-center gap-2 text-sm text-neutral-500"><UsersRound className="h-4 w-4" />{total} 位</div>{step < 4 ? <Button type="button" onClick={next}>下一步</Button> : <Button disabled={busy || !preview}>{busy ? '正在创建…' : '确认并提交'}</Button>}</div>
  </form>;
}
