import { Braces, FileSpreadsheet, Plus, X } from 'lucide-react';
import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { EmptyState, ErrorState, LoadingState } from '@/components/states';
import { api, patch, post } from '@/lib/api';
import { CustomVariable } from '@/types';

const modes = { FIXED: '固定值', RANDOM: '随机取值', SEQUENCE: '按好友顺序' } as const;
const builtIns = [{ name: 'friend_name', label: '好友称呼' }, { name: 'date', label: '日期' }, { name: 'time', label: '时间' }, { name: 'weekday', label: '星期' }, { name: 'random_quote', label: '随机语录' }, { name: 'warm_greeting', label: '温馨问候' }];
const splitValues = (value: string) => value.split(/[，,；;\n\t]+/).map((item) => item.trim()).filter(Boolean);

export function VariablesPage() {
  const [items, setItems] = useState<CustomVariable[]>(); const [error, setError] = useState(''); const [editing, setEditing] = useState<Partial<CustomVariable> & { rawValues?: string }>(); const [busy, setBusy] = useState(false);
  const load = () => api<CustomVariable[]>('/variables').then(setItems).catch((reason) => setError(reason.message));
  useEffect(() => { void load(); }, []);
  const open = (item?: CustomVariable) => { if (item?.source === 'API') return; setEditing(item ? { ...item, rawValues: item.values.map((value) => value.value).join('\n') } : { name: '', displayName: '', mode: 'FIXED', rawValues: '' }); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; const values = splitValues(editing.rawValues ?? ''); if (!editing.name?.trim() || !editing.displayName?.trim() || !values.length) return setError('请完整填写变量名称、显示名称和候选值'); setBusy(true); try { const body = { name: editing.name, displayName: editing.displayName, mode: editing.mode, values }; editing.id ? await patch(`/variables/${editing.id}`, body) : await post('/variables', body); setEditing(undefined); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  const readBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = () => reject(new Error('读取文件失败')); reader.readAsDataURL(file); });
  const importFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const name = window.prompt('变量名（英文、数字或下划线）'); if (!name) return; const displayName = window.prompt('显示名称', name); if (!displayName) return; const mode = window.prompt('取值方式：FIXED / RANDOM / SEQUENCE', 'FIXED')?.toUpperCase(); if (!['FIXED', 'RANDOM', 'SEQUENCE'].includes(mode || '')) return setError('取值方式无效'); setBusy(true); try { const base64 = await readBase64(file); await post('/imports/variables/file/import', { fileName: file.name, base64, name, displayName, mode }); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } };
  return <div className="page-enter space-y-6"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.22em] text-neutral-400">Variable Studio</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em]">内容变量</h1><p className="mt-2 text-sm text-neutral-500">固定、随机或按稳定好友顺序填充，任务提交后冻结候选值。</p></div><div className="flex gap-2"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-neutral-300 bg-white px-4 text-sm font-medium hover:bg-neutral-100"><FileSpreadsheet className="h-4 w-4" />导入 CSV/XLSX<input hidden type="file" accept=".csv,.xlsx,.xls" onChange={importFile} /></label><Button onClick={() => open()}><Plus className="h-4 w-4" />创建变量</Button></div></header>{error && <ErrorState message={error} retry={load} />}
    <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-neutral-400">内置变量</p><div className="mt-4 flex flex-wrap gap-2">{builtIns.map((item) => <span key={item.name} className="rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2 text-xs"><b>{`{{${item.name}}}`}</b><span className="ml-2 text-neutral-400">{item.label}</span></span>)}</div></Card>
    {!items ? <LoadingState /> : !items.length ? <EmptyState title="还没有自定义变量" detail="例如创建 product_name，并录入多个产品名称候选值。" /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Card key={item.id} className="p-5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-700 text-white"><Braces className="h-4 w-4" /></div><span className="font-mono text-[10px] text-neutral-400">{item.source === 'API' ? 'API' : `V${item.version}`}</span></div><p className="mt-5 font-mono text-sm">{`{{${item.name}}}`}</p><h2 className="mt-1 text-lg font-semibold">{item.displayName}</h2><p className="mt-2 text-xs text-neutral-500">{item.source === 'API' ? '外部 API 动态值 · 任务提交时获取' : `${modes[item.mode]} · ${item.values.length} 个候选值`}</p><div className="mt-4 flex flex-wrap gap-1.5">{item.values.slice(0, 4).map((value) => <span key={value.id} className="max-w-full truncate rounded bg-neutral-100 px-2 py-1 text-xs text-neutral-600">{value.value}</span>)}</div>{item.source === 'API' ? <p className="mt-5 text-center text-xs text-neutral-400">由管理员配置，只读</p> : <Button className="mt-5 w-full" variant="outline" onClick={() => open(item)}>编辑变量</Button>}</Card>)}</div>}
    {editing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-4" onClick={() => setEditing(undefined)}><Card className="w-full max-w-xl rounded-b-none p-6 shadow-2xl sm:rounded-xl" onClick={(event) => event.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-semibold">{editing.id ? '编辑变量' : '创建变量'}</h2><Button variant="ghost" size="icon" onClick={() => setEditing(undefined)}><X className="h-4 w-4" /></Button></div><form className="mt-6 space-y-4" onSubmit={save}><div className="grid grid-cols-2 gap-3"><label><span className="field-label">变量名</span><Input value={editing.name ?? ''} onChange={(e) => setEditing({ ...editing, name: e.target.value })} placeholder="product_name" /></label><label><span className="field-label">显示名称</span><Input value={editing.displayName ?? ''} onChange={(e) => setEditing({ ...editing, displayName: e.target.value })} placeholder="产品名称" /></label></div><label><span className="field-label">取值方式</span><select className="select" value={editing.mode} onChange={(e) => setEditing({ ...editing, mode: e.target.value as CustomVariable['mode'] })}>{Object.entries(modes).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="field-label">候选值</span><textarea className="textarea min-h-48" value={editing.rawValues ?? ''} onChange={(e) => setEditing({ ...editing, rawValues: e.target.value })} placeholder={'产品 A\n产品 B\n产品 C'} /><span className="field-help">支持换行、逗号或分号粘贴；空值会被过滤。</span></label><Button className="w-full" disabled={busy}>{busy ? '保存中…' : '保存变量'}</Button></form></Card></div>}
  </div>;
}
