import { post, request } from '../../services/api';

type Plan = { id: string; name: string; description: string; priceFen: number; membershipDays: number; messageQuota: number };

Page({
  data: { scene: '', order: null as any, plans: [] as Plan[], virtualOrder: null as any, loading: false, error: '', paid: false, virtualPaid: false },
  onLoad(options: any) { const scene = options.scene || wx.getStorageSync('wechatsend_pending_scene'); if (!scene) return void request<Plan[]>('/virtual-payment/plans').then((plans) => this.setData({ plans })).catch((error) => this.setData({ error: (error as Error).message })); this.setData({ scene }); void request<any>(`/payments/scan/${encodeURIComponent(scene)}`).then((order) => this.setData({ order })).catch((error) => this.setData({ error: (error as Error).message })); },
  async waitForCallback(orderId: string) { for (let attempt = 0; attempt < 8; attempt += 1) { const order = await request<any>(`/payments/orders/${orderId}`); if (order.status === 'SUCCESS') return true; if (['FAILED', 'CLOSED', 'REFUNDED'].includes(order.status)) return false; await new Promise((resolve) => setTimeout(resolve, 1000)); } return false; },
  async pay() { if (!this.data.order) return; this.setData({ loading: true, error: '' }); try { const params = await post<any>(`/payments/orders/${this.data.order.id}/checkout`); await new Promise<void>((resolve, reject) => wx.requestPayment({ ...params, success: () => resolve(), fail: reject })); const paid = await this.waitForCallback(this.data.order.id); if (paid) { this.setData({ paid: true }); wx.removeStorageSync('wechatsend_pending_scene'); } else this.setData({ error: '支付已完成操作，但服务端尚未确认结果，请稍后在订单记录中查看。' }); } catch (error) { this.setData({ error: (error as Error).message || '支付未完成' }); } finally { this.setData({ loading: false }); } },
  async waitForVirtual(orderId: string) { for (let attempt = 0; attempt < 20; attempt += 1) { const order = await post<any>(`/virtual-payment/orders/${orderId}/query`); this.setData({ virtualOrder: order }); if (order.status === 'DELIVERED') return true; if (['FAILED', 'CLOSED', 'REFUNDED'].includes(order.status)) return false; await new Promise((resolve) => setTimeout(resolve, 3000)); } return false; },
  async buyVirtual(event: WechatMiniprogram.TouchEvent) { const planId = String(event.currentTarget.dataset.planId || ''); if (!planId) return; this.setData({ loading: true, error: '' }); try { const created = await post<any>('/virtual-payment/orders', { planId, quantity: 1 }); this.setData({ virtualOrder: created }); const requestVirtualPayment = (wx as any).requestVirtualPayment as (options: Record<string, unknown>) => void; if (typeof requestVirtualPayment !== 'function') throw new Error('当前微信版本不支持虚拟支付，请升级微信后重试'); await new Promise<void>((resolve, reject) => requestVirtualPayment({ ...created.payData, success: () => resolve(), fail: reject })); const delivered = await this.waitForVirtual(created.id); if (delivered) this.setData({ virtualPaid: true }); else this.setData({ error: '支付已完成，但服务端还在等待微信发货推送，请稍后查看权益。' }); } catch (error) { this.setData({ error: (error as Error).message || '支付未完成' }); } finally { this.setData({ loading: false }); } },
});
