import { Check, ExternalLink, KeyRound, Plus, Settings2, Trash2 } from 'lucide-react';
import type { FormEvent } from 'react';
import { DeleteConfirm } from '@/components/delete-confirm';
import { FormField } from '@/components/form-field';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { AiChannel, ApiIntegration } from '@/types';
import type { ChannelDraft, FeatureFlag, IntegrationDraft, IntegrationVariableDraft } from './types';
import { flagLabels } from './types';

export function FeatureFlagsPanel({ flags, onToggle }: { flags: FeatureFlag[]; onToggle: (flag: FeatureFlag) => void }) {
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings2 />业务能力</CardTitle><CardDescription>控制普通用户可以看到和使用的产品能力。</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{flags.map((flag) => <button key={flag.key} type="button" className={`rounded-xl border p-4 text-left transition-colors ${flag.enabled ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-neutral-200 hover:border-neutral-500'}`} onClick={() => onToggle(flag)}><span className="flex items-start justify-between gap-3"><b className="text-sm leading-5">{flagLabels[flag.key] || flag.key}</b>{flag.enabled ? <Check /> : null}</span><span className={`mt-3 block text-xs ${flag.enabled ? 'text-neutral-400' : 'text-neutral-500'}`}>{flag.enabled ? '对用户开放' : '暂未开放'}</span></button>)}</CardContent></Card>;
}

export function AiChannelsPanel({ channels, draft, busy, onDraft, onSave, onDeleteChannel, onDeleteModel, onAddModel, onTestModel }: { channels: AiChannel[]; draft: ChannelDraft; busy: boolean; onDraft: (draft: ChannelDraft) => void; onSave: (event: FormEvent) => void; onDeleteChannel: (item: AiChannel) => Promise<void>; onDeleteModel: (model: AiChannel['models'][number]) => Promise<void>; onAddModel: (channelId: string) => void; onTestModel: (model: AiChannel['models'][number]) => void }) {
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]">
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound />已接入通道</CardTitle><CardDescription>模型归属于通道；删除通道会同时删除其模型。</CardDescription></CardHeader><CardContent className="space-y-3">{channels.map((item) => <article key={item.id} className="rounded-xl border border-neutral-200 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b>{item.name}</b><p className="mt-1 truncate font-mono text-xs text-neutral-400">{item.baseUrl}</p><p className="mt-2 text-xs text-neutral-500">{item.hasApiKey ? 'API Key 已安全保存' : '未配置密钥'}</p></div><DeleteConfirm title={`删除“${item.name}”？`} description="该通道和所属模型会永久删除，使用这些模型的新请求将无法执行。" busy={busy} onConfirm={() => onDeleteChannel(item)} trigger={<Button type="button" size="sm" variant="ghost" className="text-red-600 hover:bg-red-50"><Trash2 />删除</Button>} /></div><div className="mt-4 space-y-2">{item.models.map((model) => <div key={model.id} className="flex items-center justify-between gap-2 rounded-lg bg-neutral-50 px-3 py-2 text-xs"><span className="min-w-0 truncate"><span className="font-medium">{model.displayName || model.name}</span><span className="ml-2 font-mono text-neutral-400">{model.name}</span></span><span className="flex shrink-0 gap-1"><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={() => onTestModel(model)}>测试</Button><DeleteConfirm title={`删除模型“${model.displayName || model.name}”？`} description="删除后不可恢复，请确认没有业务继续使用该模型。" busy={busy} onConfirm={() => onDeleteModel(model)} trigger={<Button type="button" size="sm" variant="ghost" className="text-red-600 hover:bg-red-50">删除</Button>} /></span></div>)}{!item.models.length ? <p className="rounded-lg bg-neutral-50 p-3 text-xs text-neutral-500">还没有模型。</p> : null}</div><Button type="button" size="sm" variant="outline" className="mt-3" disabled={busy} onClick={() => onAddModel(item.id)}><Plus />添加模型</Button></article>)}{!channels.length ? <p className="py-8 text-center text-sm text-neutral-500">还没有 AI 通道。</p> : null}</CardContent></Card>
    <Card><CardHeader><CardTitle>接入新通道</CardTitle><CardDescription>兼容 OpenAI API 格式的模型服务。</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={onSave}><TextField label="名称" value={draft.name} onChange={(value) => onDraft({ ...draft, name: value })} placeholder="OpenAI 主通道" /><TextField label="Base URL（包含 /v1）" value={draft.baseUrl} onChange={(value) => onDraft({ ...draft, baseUrl: value })} placeholder="https://api.openai.com/v1" /><TextField label="API Key" value={draft.apiKey} onChange={(value) => onDraft({ ...draft, apiKey: value })} placeholder="sk-..." type="password" /><TextField label="首个模型名" value={draft.model} onChange={(value) => onDraft({ ...draft, model: value })} placeholder="gpt-4o-mini" /><Button className="w-full" disabled={busy}><Plus />保存通道</Button></form></CardContent></Card>
  </div>;
}

export function IntegrationsPanel({ items, draft, busy, onDraft, onSave, onTest, onDelete }: { items: ApiIntegration[]; draft: IntegrationDraft; busy: boolean; onDraft: (draft: IntegrationDraft) => void; onSave: (event: FormEvent) => void; onTest: (id: string) => void; onDelete: (item: ApiIntegration) => Promise<void> }) {
  const updateVariable = (index: number, key: keyof IntegrationVariableDraft, value: string) => onDraft({ ...draft, variables: draft.variables.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) });
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]">
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ExternalLink />外部变量接口</CardTitle><CardDescription>把接口响应字段映射为可插入文案的变量。</CardDescription></CardHeader><CardContent className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-neutral-200 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><b>{item.name}</b><p className="mt-1 truncate font-mono text-xs text-neutral-400">{item.method} · {item.url}</p></div><DeleteConfirm title={`删除“${item.name}”？`} description="接口及其变量映射会永久删除，引用这些变量的模板将需要修改。" busy={busy} onConfirm={() => onDelete(item)} trigger={<Button type="button" size="sm" variant="ghost" className="text-red-600 hover:bg-red-50"><Trash2 />删除</Button>} /></div><div className="mt-3 flex flex-wrap gap-1.5">{item.variables.map((variable) => <span key={variable.id} className="rounded bg-neutral-100 px-2 py-1 font-mono text-[11px]">{'{{'}{variable.name}{'}}'} → {variable.responsePath}</span>)}</div><Button type="button" size="sm" variant="outline" className="mt-3" disabled={busy} onClick={() => onTest(item.id)}>测试请求</Button></article>)}{!items.length ? <p className="py-8 text-center text-sm text-neutral-500">还没有外部变量接口。</p> : null}</CardContent></Card>
    <Card><CardHeader><CardTitle>接入新接口</CardTitle><CardDescription>请求头会加密保存，测试成功后再用于正式任务。</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={onSave}><TextField label="名称" value={draft.name} onChange={(value) => onDraft({ ...draft, name: value })} placeholder="今日天气" /><TextField label="URL" value={draft.url} onChange={(value) => onDraft({ ...draft, url: value })} placeholder="https://example.com/weather" /><FormField label="方法"><select className="select" value={draft.method} onChange={(event) => onDraft({ ...draft, method: event.target.value })}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option></select></FormField><FormField label="请求头 JSON（选填）"><Textarea className="min-h-20 font-mono text-xs" value={draft.headers} onChange={(event) => onDraft({ ...draft, headers: event.target.value })} /></FormField><FormField label="请求参数 JSON"><Textarea className="min-h-20 font-mono text-xs" value={draft.params} onChange={(event) => onDraft({ ...draft, params: event.target.value })} /></FormField><div className="space-y-3"><div className="flex items-center justify-between"><span className="field-label mb-0">响应变量</span><Button type="button" size="sm" variant="outline" onClick={() => onDraft({ ...draft, variables: [...draft.variables, { name: '', displayName: '', responsePath: '' }] })}><Plus />添加变量</Button></div>{draft.variables.map((variable, index) => <div key={index} className="rounded-xl border border-neutral-200 p-3"><div className="mb-2 flex items-center justify-between text-xs font-semibold text-neutral-500">变量 {index + 1}{draft.variables.length > 1 ? <Button type="button" size="sm" variant="ghost" onClick={() => onDraft({ ...draft, variables: draft.variables.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 />删除</Button> : null}</div><div className="grid gap-3 sm:grid-cols-2"><TextField label="变量名（英文）" value={variable.name} onChange={(value) => updateVariable(index, 'name', value)} placeholder="weather_text" /><TextField label="显示名称" value={variable.displayName} onChange={(value) => updateVariable(index, 'displayName', value)} placeholder="天气" /></div><div className="mt-3"><TextField label="响应路径" value={variable.responsePath} onChange={(value) => updateVariable(index, 'responsePath', value)} placeholder="data.weather.text" /></div></div>)}</div><Button className="w-full" disabled={busy}><Plus />保存外部 API</Button></form></CardContent></Card>
  </div>;
}

export function TextField({ label, value, onChange, placeholder, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) {
  return <FormField label={label}><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required /></FormField>;
}
